/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.cookies.service.base;

import com.liferay.cookies.model.ConsentPreference;
import com.liferay.cookies.service.ConsentPreferenceLocalService;
import com.liferay.cookies.service.persistence.ConsentPreferencePersistence;
import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.CurrentConnectionUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;

import java.io.Serializable;

import java.sql.Connection;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the consent preference local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.cookies.service.impl.ConsentPreferenceLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.cookies.service.impl.ConsentPreferenceLocalServiceImpl
 * @generated
 */
public abstract class ConsentPreferenceLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, ConsentPreferenceLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ConsentPreferenceLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.cookies.service.ConsentPreferenceLocalServiceUtil</code>.
	 */

	/**
	 * Adds the consent preference to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ConsentPreferenceLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param consentPreference the consent preference
	 * @return the consent preference that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ConsentPreference addConsentPreference(
		ConsentPreference consentPreference) {

		consentPreference.setNew(true);

		return consentPreferencePersistence.update(consentPreference);
	}

	/**
	 * Creates a new consent preference with the primary key. Does not add the consent preference to the database.
	 *
	 * @param consentPreferenceId the primary key for the new consent preference
	 * @return the new consent preference
	 */
	@Override
	@Transactional(enabled = false)
	public ConsentPreference createConsentPreference(long consentPreferenceId) {
		return consentPreferencePersistence.create(consentPreferenceId);
	}

	/**
	 * Deletes the consent preference with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ConsentPreferenceLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param consentPreferenceId the primary key of the consent preference
	 * @return the consent preference that was removed
	 * @throws PortalException if a consent preference with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ConsentPreference deleteConsentPreference(long consentPreferenceId)
		throws PortalException {

		return consentPreferencePersistence.remove(consentPreferenceId);
	}

	/**
	 * Deletes the consent preference from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ConsentPreferenceLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param consentPreference the consent preference
	 * @return the consent preference that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ConsentPreference deleteConsentPreference(
		ConsentPreference consentPreference) {

		return consentPreferencePersistence.remove(consentPreference);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return consentPreferencePersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			ConsentPreference.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return consentPreferencePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.cookies.model.impl.ConsentPreferenceModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return consentPreferencePersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.cookies.model.impl.ConsentPreferenceModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return consentPreferencePersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return consentPreferencePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return consentPreferencePersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public ConsentPreference fetchConsentPreference(long consentPreferenceId) {
		return consentPreferencePersistence.fetchByPrimaryKey(
			consentPreferenceId);
	}

	/**
	 * Returns the consent preference with the primary key.
	 *
	 * @param consentPreferenceId the primary key of the consent preference
	 * @return the consent preference
	 * @throws PortalException if a consent preference with the primary key could not be found
	 */
	@Override
	public ConsentPreference getConsentPreference(long consentPreferenceId)
		throws PortalException {

		return consentPreferencePersistence.findByPrimaryKey(
			consentPreferenceId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			consentPreferenceLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ConsentPreference.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("consentPreferenceId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			consentPreferenceLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(ConsentPreference.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"consentPreferenceId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			consentPreferenceLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ConsentPreference.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("consentPreferenceId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return consentPreferencePersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		if (_log.isWarnEnabled()) {
			_log.warn(
				"Implement ConsentPreferenceLocalServiceImpl#deleteConsentPreference(ConsentPreference) to avoid orphaned data");
		}

		return consentPreferenceLocalService.deleteConsentPreference(
			(ConsentPreference)persistedModel);
	}

	@Override
	public BasePersistence<ConsentPreference> getBasePersistence() {
		return consentPreferencePersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return consentPreferencePersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the consent preferences.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.cookies.model.impl.ConsentPreferenceModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of consent preferences
	 * @param end the upper bound of the range of consent preferences (not inclusive)
	 * @return the range of consent preferences
	 */
	@Override
	public List<ConsentPreference> getConsentPreferences(int start, int end) {
		return consentPreferencePersistence.findAll(start, end);
	}

	/**
	 * Returns the number of consent preferences.
	 *
	 * @return the number of consent preferences
	 */
	@Override
	public int getConsentPreferencesCount() {
		return consentPreferencePersistence.countAll();
	}

	/**
	 * Updates the consent preference in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ConsentPreferenceLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param consentPreference the consent preference
	 * @return the consent preference that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ConsentPreference updateConsentPreference(
		ConsentPreference consentPreference) {

		return consentPreferencePersistence.update(consentPreference);
	}

	@Deactivate
	protected void deactivate() {
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			ConsentPreferenceLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		consentPreferenceLocalService = (ConsentPreferenceLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ConsentPreferenceLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ConsentPreference.class;
	}

	protected String getModelClassName() {
		return ConsentPreference.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		DataSource dataSource = consentPreferencePersistence.getDataSource();

		DB db = DBManagerUtil.getDB();

		Connection currentConnection = CurrentConnectionUtil.getConnection(
			dataSource);

		try {
			if (currentConnection != null) {
				db.runSQL(currentConnection, new String[] {sql});

				return;
			}

			try (Connection connection = dataSource.getConnection()) {
				db.runSQL(connection, new String[] {sql});
			}
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected ConsentPreferenceLocalService consentPreferenceLocalService;

	@Reference
	protected ConsentPreferencePersistence consentPreferencePersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	private static final Log _log = LogFactoryUtil.getLog(
		ConsentPreferenceLocalServiceBaseImpl.class);

}
// LIFERAY-SERVICE-BUILDER-HASH:-1702984721