/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.cookies.uad.anonymizer;

import com.liferay.asset.kernel.model.AssetEntry;
import com.liferay.asset.kernel.service.AssetEntryLocalService;
import com.liferay.cookies.model.ConsentPreference;
import com.liferay.cookies.service.ConsentPreferenceLocalService;
import com.liferay.cookies.uad.constants.CookiesUADConstants;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.User;
import com.liferay.user.associated.data.anonymizer.DynamicQueryUADAnonymizer;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the consent preference UAD anonymizer.
 *
 * <p>
 * This implementation exists only as a container for the default methods
 * generated by ServiceBuilder. All custom service methods should be put in
 * {@link ConsentPreferenceUADAnonymizer}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @generated
 */
public abstract class BaseConsentPreferenceUADAnonymizer
	extends DynamicQueryUADAnonymizer<ConsentPreference> {

	@Override
	public void autoAnonymize(
			ConsentPreference consentPreference, long userId,
			User anonymousUser)
		throws PortalException {

		if (consentPreference.getUserId() == userId) {
			consentPreference.setUserId(anonymousUser.getUserId());
			consentPreference.setUserName(anonymousUser.getFullName());

			autoAnonymizeAssetEntry(consentPreference, anonymousUser);
		}

		consentPreferenceLocalService.updateConsentPreference(
			consentPreference);
	}

	@Override
	public void delete(ConsentPreference consentPreference)
		throws PortalException {

		consentPreferenceLocalService.deleteConsentPreference(
			consentPreference);
	}

	@Override
	public Class<ConsentPreference> getTypeClass() {
		return ConsentPreference.class;
	}

	protected void autoAnonymizeAssetEntry(
		ConsentPreference consentPreference, User anonymousUser) {

		AssetEntry assetEntry = fetchAssetEntry(consentPreference);

		if (assetEntry != null) {
			assetEntry.setUserId(anonymousUser.getUserId());
			assetEntry.setUserName(anonymousUser.getFullName());

			assetEntryLocalService.updateAssetEntry(assetEntry);
		}
	}

	@Override
	protected ActionableDynamicQuery doGetActionableDynamicQuery() {
		return consentPreferenceLocalService.getActionableDynamicQuery();
	}

	@Override
	protected String[] doGetUserIdFieldNames() {
		return CookiesUADConstants.USER_ID_FIELD_NAMES_CONSENT_PREFERENCE;
	}

	protected AssetEntry fetchAssetEntry(ConsentPreference consentPreference) {
		return assetEntryLocalService.fetchEntry(
			ConsentPreference.class.getName(),
			consentPreference.getConsentPreferenceId());
	}

	@Reference
	protected AssetEntryLocalService assetEntryLocalService;

	@Reference
	protected ConsentPreferenceLocalService consentPreferenceLocalService;

}