##
## Exclusions
##
## See https://github.com/liferay/liferay-portal/blob/master/source-formatter.properties
## for available properties.
##

    source.check.JavaModuleComponentCheck.allowedClassNames=\
        com.liferay.saml.runtime.configuration.SamlKeystoreManagerMetaTypeRegistrator

    source.formatter.excludes=\
        modules/dxp/apps/saml/saml-api/src/main/java/com/liferay/saml/util/JspUtil.java

##
## Git
##

    git.liferay.portal.branch=master