/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.security.audit.storage.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AuditPseudonym service. Represents a row in the &quot;Audit_AuditPseudonym&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.security.audit.storage.model.impl.AuditPseudonymModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.security.audit.storage.model.impl.AuditPseudonymImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AuditPseudonym
 * @generated
 */
@ProviderType
public interface AuditPseudonymModel
	extends BaseModel<AuditPseudonym>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a audit pseudonym model instance should use the {@link AuditPseudonym} interface instead.
	 */

	/**
	 * Returns the primary key of this audit pseudonym.
	 *
	 * @return the primary key of this audit pseudonym
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this audit pseudonym.
	 *
	 * @param primaryKey the primary key of this audit pseudonym
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the audit pseudonym ID of this audit pseudonym.
	 *
	 * @return the audit pseudonym ID of this audit pseudonym
	 */
	public long getAuditPseudonymId();

	/**
	 * Sets the audit pseudonym ID of this audit pseudonym.
	 *
	 * @param auditPseudonymId the audit pseudonym ID of this audit pseudonym
	 */
	public void setAuditPseudonymId(long auditPseudonymId);

	/**
	 * Returns the company ID of this audit pseudonym.
	 *
	 * @return the company ID of this audit pseudonym
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this audit pseudonym.
	 *
	 * @param companyId the company ID of this audit pseudonym
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this audit pseudonym.
	 *
	 * @return the create date of this audit pseudonym
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this audit pseudonym.
	 *
	 * @param createDate the create date of this audit pseudonym
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the context name of this audit pseudonym.
	 *
	 * @return the context name of this audit pseudonym
	 */
	@AutoEscape
	public String getContextName();

	/**
	 * Sets the context name of this audit pseudonym.
	 *
	 * @param contextName the context name of this audit pseudonym
	 */
	public void setContextName(String contextName);

	/**
	 * Returns the field category of this audit pseudonym.
	 *
	 * @return the field category of this audit pseudonym
	 */
	@AutoEscape
	public String getFieldCategory();

	/**
	 * Sets the field category of this audit pseudonym.
	 *
	 * @param fieldCategory the field category of this audit pseudonym
	 */
	public void setFieldCategory(String fieldCategory);

	/**
	 * Returns the value of this audit pseudonym.
	 *
	 * @return the value of this audit pseudonym
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this audit pseudonym.
	 *
	 * @param value the value of this audit pseudonym
	 */
	public void setValue(String value);

	@Override
	public AuditPseudonym cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-940874974