/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.security.ldap.persistence.model;

import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the LDAPServerAttributeRel service. Represents a row in the &quot;LDAPServerAttributeRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.security.ldap.persistence.model.impl.LDAPServerAttributeRelModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.security.ldap.persistence.model.impl.LDAPServerAttributeRelImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LDAPServerAttributeRel
 * @generated
 */
@ProviderType
public interface LDAPServerAttributeRelModel
	extends AttachedModel, BaseModel<LDAPServerAttributeRel>, MVCCModel,
			ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ldap server attribute rel model instance should use the {@link LDAPServerAttributeRel} interface instead.
	 */

	/**
	 * Returns the primary key of this ldap server attribute rel.
	 *
	 * @return the primary key of this ldap server attribute rel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ldap server attribute rel.
	 *
	 * @param primaryKey the primary key of this ldap server attribute rel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this ldap server attribute rel.
	 *
	 * @return the mvcc version of this ldap server attribute rel
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this ldap server attribute rel.
	 *
	 * @param mvccVersion the mvcc version of this ldap server attribute rel
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the ldap server attribute rel ID of this ldap server attribute rel.
	 *
	 * @return the ldap server attribute rel ID of this ldap server attribute rel
	 */
	public long getLdapServerAttributeRelId();

	/**
	 * Sets the ldap server attribute rel ID of this ldap server attribute rel.
	 *
	 * @param ldapServerAttributeRelId the ldap server attribute rel ID of this ldap server attribute rel
	 */
	public void setLdapServerAttributeRelId(long ldapServerAttributeRelId);

	/**
	 * Returns the company ID of this ldap server attribute rel.
	 *
	 * @return the company ID of this ldap server attribute rel
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this ldap server attribute rel.
	 *
	 * @param companyId the company ID of this ldap server attribute rel
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the ldap server ID of this ldap server attribute rel.
	 *
	 * @return the ldap server ID of this ldap server attribute rel
	 */
	public long getLdapServerId();

	/**
	 * Sets the ldap server ID of this ldap server attribute rel.
	 *
	 * @param ldapServerId the ldap server ID of this ldap server attribute rel
	 */
	public void setLdapServerId(long ldapServerId);

	/**
	 * Returns the fully qualified class name of this ldap server attribute rel.
	 *
	 * @return the fully qualified class name of this ldap server attribute rel
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this ldap server attribute rel.
	 *
	 * @return the class name ID of this ldap server attribute rel
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this ldap server attribute rel.
	 *
	 * @param classNameId the class name ID of this ldap server attribute rel
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this ldap server attribute rel.
	 *
	 * @return the class pk of this ldap server attribute rel
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this ldap server attribute rel.
	 *
	 * @param classPK the class pk of this ldap server attribute rel
	 */
	@Override
	public void setClassPK(long classPK);

	@Override
	public LDAPServerAttributeRel cloneWithOriginalValues();

}