/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.cookies.model.impl;

import com.liferay.cookies.model.ConsentPreference;
import com.liferay.cookies.model.ConsentPreferenceModel;
import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ConsentPreference service. Represents a row in the &quot;ConsentPreference&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ConsentPreferenceModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ConsentPreferenceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ConsentPreferenceImpl
 * @generated
 */
@JSON(strict = true)
public class ConsentPreferenceModelImpl
	extends BaseModelImpl<ConsentPreference> implements ConsentPreferenceModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a consent preference model instance should use the <code>ConsentPreference</code> interface instead.
	 */
	public static final String TABLE_NAME = "ConsentPreference";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"consentPreferenceId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"domain", Types.VARCHAR},
		{"expirationDate", Types.TIMESTAMP}, {"name", Types.VARCHAR},
		{"value", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("consentPreferenceId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("domain", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("expirationDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("value", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ConsentPreference (mvccVersion LONG default 0 not null,consentPreferenceId LONG not null primary key,companyId LONG,userId LONG,userName VARCHAR(75) null,domain VARCHAR(75) null,expirationDate DATE null,name VARCHAR(75) null,value VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table ConsentPreference";

	public static final String ORDER_BY_JPQL =
		" ORDER BY consentPreference.consentPreferenceId DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ConsentPreference.consentPreferenceId DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long DOMAIN_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long EXPIRATIONDATE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CONSENTPREFERENCEID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ConsentPreferenceModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _consentPreferenceId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setConsentPreferenceId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _consentPreferenceId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ConsentPreference.class;
	}

	@Override
	public String getModelClassName() {
		return ConsentPreference.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ConsentPreference, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ConsentPreference, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ConsentPreference, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ConsentPreference)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ConsentPreference, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ConsentPreference, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ConsentPreference)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ConsentPreference, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ConsentPreference, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<ConsentPreference, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<ConsentPreference, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<ConsentPreference, Object>>();

			attributeGetterFunctions.put(
				"mvccVersion", ConsentPreference::getMvccVersion);
			attributeGetterFunctions.put(
				"consentPreferenceId",
				ConsentPreference::getConsentPreferenceId);
			attributeGetterFunctions.put(
				"companyId", ConsentPreference::getCompanyId);
			attributeGetterFunctions.put(
				"userId", ConsentPreference::getUserId);
			attributeGetterFunctions.put(
				"userName", ConsentPreference::getUserName);
			attributeGetterFunctions.put(
				"domain", ConsentPreference::getDomain);
			attributeGetterFunctions.put(
				"expirationDate", ConsentPreference::getExpirationDate);
			attributeGetterFunctions.put("name", ConsentPreference::getName);
			attributeGetterFunctions.put("value", ConsentPreference::getValue);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<ConsentPreference, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<ConsentPreference, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap
						<String, BiConsumer<ConsentPreference, ?>>();

			attributeSetterBiConsumers.put(
				"mvccVersion",
				(BiConsumer<ConsentPreference, Long>)
					ConsentPreference::setMvccVersion);
			attributeSetterBiConsumers.put(
				"consentPreferenceId",
				(BiConsumer<ConsentPreference, Long>)
					ConsentPreference::setConsentPreferenceId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<ConsentPreference, Long>)
					ConsentPreference::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId",
				(BiConsumer<ConsentPreference, Long>)
					ConsentPreference::setUserId);
			attributeSetterBiConsumers.put(
				"userName",
				(BiConsumer<ConsentPreference, String>)
					ConsentPreference::setUserName);
			attributeSetterBiConsumers.put(
				"domain",
				(BiConsumer<ConsentPreference, String>)
					ConsentPreference::setDomain);
			attributeSetterBiConsumers.put(
				"expirationDate",
				(BiConsumer<ConsentPreference, Date>)
					ConsentPreference::setExpirationDate);
			attributeSetterBiConsumers.put(
				"name",
				(BiConsumer<ConsentPreference, String>)
					ConsentPreference::setName);
			attributeSetterBiConsumers.put(
				"value",
				(BiConsumer<ConsentPreference, String>)
					ConsentPreference::setValue);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public long getConsentPreferenceId() {
		return _consentPreferenceId;
	}

	@Override
	public void setConsentPreferenceId(long consentPreferenceId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_consentPreferenceId = consentPreferenceId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public String getDomain() {
		if (_domain == null) {
			return "";
		}
		else {
			return _domain;
		}
	}

	@Override
	public void setDomain(String domain) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_domain = domain;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalDomain() {
		return getColumnOriginalValue("domain");
	}

	@JSON
	@Override
	public Date getExpirationDate() {
		return _expirationDate;
	}

	@Override
	public void setExpirationDate(Date expirationDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_expirationDate = expirationDate;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public Date getOriginalExpirationDate() {
		return getColumnOriginalValue("expirationDate");
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	@JSON
	@Override
	public String getValue() {
		if (_value == null) {
			return "";
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_value = value;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), ConsentPreference.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ConsentPreference toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ConsentPreference>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ConsentPreferenceImpl consentPreferenceImpl =
			new ConsentPreferenceImpl();

		consentPreferenceImpl.setMvccVersion(getMvccVersion());
		consentPreferenceImpl.setConsentPreferenceId(getConsentPreferenceId());
		consentPreferenceImpl.setCompanyId(getCompanyId());
		consentPreferenceImpl.setUserId(getUserId());
		consentPreferenceImpl.setUserName(getUserName());
		consentPreferenceImpl.setDomain(getDomain());
		consentPreferenceImpl.setExpirationDate(getExpirationDate());
		consentPreferenceImpl.setName(getName());
		consentPreferenceImpl.setValue(getValue());

		consentPreferenceImpl.resetOriginalValues();

		return consentPreferenceImpl;
	}

	@Override
	public ConsentPreference cloneWithOriginalValues() {
		ConsentPreferenceImpl consentPreferenceImpl =
			new ConsentPreferenceImpl();

		consentPreferenceImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		consentPreferenceImpl.setConsentPreferenceId(
			this.<Long>getColumnOriginalValue("consentPreferenceId"));
		consentPreferenceImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		consentPreferenceImpl.setUserId(
			this.<Long>getColumnOriginalValue("userId"));
		consentPreferenceImpl.setUserName(
			this.<String>getColumnOriginalValue("userName"));
		consentPreferenceImpl.setDomain(
			this.<String>getColumnOriginalValue("domain"));
		consentPreferenceImpl.setExpirationDate(
			this.<Date>getColumnOriginalValue("expirationDate"));
		consentPreferenceImpl.setName(
			this.<String>getColumnOriginalValue("name"));
		consentPreferenceImpl.setValue(
			this.<String>getColumnOriginalValue("value"));

		return consentPreferenceImpl;
	}

	@Override
	public int compareTo(ConsentPreference consentPreference) {
		int value = 0;

		if (getConsentPreferenceId() <
				consentPreference.getConsentPreferenceId()) {

			value = -1;
		}
		else if (getConsentPreferenceId() >
					consentPreference.getConsentPreferenceId()) {

			value = 1;
		}
		else {
			value = 0;
		}

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ConsentPreference)) {
			return false;
		}

		ConsentPreference consentPreference = (ConsentPreference)object;

		long primaryKey = consentPreference.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ConsentPreference> toCacheModel() {
		ConsentPreferenceCacheModel consentPreferenceCacheModel =
			new ConsentPreferenceCacheModel();

		consentPreferenceCacheModel.mvccVersion = getMvccVersion();

		consentPreferenceCacheModel.consentPreferenceId =
			getConsentPreferenceId();

		consentPreferenceCacheModel.companyId = getCompanyId();

		consentPreferenceCacheModel.userId = getUserId();

		consentPreferenceCacheModel.userName = getUserName();

		String userName = consentPreferenceCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			consentPreferenceCacheModel.userName = null;
		}

		consentPreferenceCacheModel.domain = getDomain();

		String domain = consentPreferenceCacheModel.domain;

		if ((domain != null) && (domain.length() == 0)) {
			consentPreferenceCacheModel.domain = null;
		}

		Date expirationDate = getExpirationDate();

		if (expirationDate != null) {
			consentPreferenceCacheModel.expirationDate =
				expirationDate.getTime();
		}
		else {
			consentPreferenceCacheModel.expirationDate = Long.MIN_VALUE;
		}

		consentPreferenceCacheModel.name = getName();

		String name = consentPreferenceCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			consentPreferenceCacheModel.name = null;
		}

		consentPreferenceCacheModel.value = getValue();

		String value = consentPreferenceCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			consentPreferenceCacheModel.value = null;
		}

		return consentPreferenceCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ConsentPreference, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ConsentPreference, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ConsentPreference, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ConsentPreference)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ConsentPreference>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ConsentPreference.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _consentPreferenceId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private String _domain;
	private Date _expirationDate;
	private String _name;
	private String _value;

	public <T> T getColumnValue(String columnName) {
		Function<ConsentPreference, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ConsentPreference)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put("consentPreferenceId", _consentPreferenceId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("domain", _domain);
		_columnOriginalValues.put("expirationDate", _expirationDate);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("value", _value);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("consentPreferenceId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("userName", 16L);

		columnBitmasks.put("domain", 32L);

		columnBitmasks.put("expirationDate", 64L);

		columnBitmasks.put("name", 128L);

		columnBitmasks.put("value", 256L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ConsentPreference _escapedModel;

}