/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.security.password.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.security.password.model.PasswordHashGenerator;
import com.liferay.portal.security.password.service.PasswordHashGeneratorLocalService;
import com.liferay.portal.security.password.service.persistence.PasswordEntryPersistence;
import com.liferay.portal.security.password.service.persistence.PasswordHashGeneratorPersistence;
import com.liferay.portal.security.password.service.persistence.PasswordMetaPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the password hash generator local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.portal.security.password.service.impl.PasswordHashGeneratorLocalServiceImpl}.
 * </p>
 *
 * @author Arthur Chan
 * @see com.liferay.portal.security.password.service.impl.PasswordHashGeneratorLocalServiceImpl
 * @generated
 */
public abstract class PasswordHashGeneratorLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   PasswordHashGeneratorLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>PasswordHashGeneratorLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.portal.security.password.service.PasswordHashGeneratorLocalServiceUtil</code>.
	 */

	/**
	 * Adds the password hash generator to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PasswordHashGeneratorLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param passwordHashGenerator the password hash generator
	 * @return the password hash generator that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public PasswordHashGenerator addPasswordHashGenerator(
		PasswordHashGenerator passwordHashGenerator) {

		passwordHashGenerator.setNew(true);

		return passwordHashGeneratorPersistence.update(passwordHashGenerator);
	}

	/**
	 * Creates a new password hash generator with the primary key. Does not add the password hash generator to the database.
	 *
	 * @param passwordHashGeneratorId the primary key for the new password hash generator
	 * @return the new password hash generator
	 */
	@Override
	@Transactional(enabled = false)
	public PasswordHashGenerator createPasswordHashGenerator(
		long passwordHashGeneratorId) {

		return passwordHashGeneratorPersistence.create(passwordHashGeneratorId);
	}

	/**
	 * Deletes the password hash generator with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PasswordHashGeneratorLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param passwordHashGeneratorId the primary key of the password hash generator
	 * @return the password hash generator that was removed
	 * @throws PortalException if a password hash generator with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public PasswordHashGenerator deletePasswordHashGenerator(
			long passwordHashGeneratorId)
		throws PortalException {

		return passwordHashGeneratorPersistence.remove(passwordHashGeneratorId);
	}

	/**
	 * Deletes the password hash generator from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PasswordHashGeneratorLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param passwordHashGenerator the password hash generator
	 * @return the password hash generator that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public PasswordHashGenerator deletePasswordHashGenerator(
		PasswordHashGenerator passwordHashGenerator) {

		return passwordHashGeneratorPersistence.remove(passwordHashGenerator);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return passwordHashGeneratorPersistence.dslQuery(dslQuery);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			PasswordHashGenerator.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return passwordHashGeneratorPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.security.password.model.impl.PasswordHashGeneratorModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return passwordHashGeneratorPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.security.password.model.impl.PasswordHashGeneratorModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return passwordHashGeneratorPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return passwordHashGeneratorPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return passwordHashGeneratorPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public PasswordHashGenerator fetchPasswordHashGenerator(
		long passwordHashGeneratorId) {

		return passwordHashGeneratorPersistence.fetchByPrimaryKey(
			passwordHashGeneratorId);
	}

	/**
	 * Returns the password hash generator with the matching UUID and company.
	 *
	 * @param uuid the password hash generator's UUID
	 * @param companyId the primary key of the company
	 * @return the matching password hash generator, or <code>null</code> if a matching password hash generator could not be found
	 */
	@Override
	public PasswordHashGenerator fetchPasswordHashGeneratorByUuidAndCompanyId(
		String uuid, long companyId) {

		return passwordHashGeneratorPersistence.fetchByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns the password hash generator with the primary key.
	 *
	 * @param passwordHashGeneratorId the primary key of the password hash generator
	 * @return the password hash generator
	 * @throws PortalException if a password hash generator with the primary key could not be found
	 */
	@Override
	public PasswordHashGenerator getPasswordHashGenerator(
			long passwordHashGeneratorId)
		throws PortalException {

		return passwordHashGeneratorPersistence.findByPrimaryKey(
			passwordHashGeneratorId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			passwordHashGeneratorLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(PasswordHashGenerator.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"passwordHashGeneratorId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			passwordHashGeneratorLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			PasswordHashGenerator.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"passwordHashGeneratorId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			passwordHashGeneratorLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(PasswordHashGenerator.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"passwordHashGeneratorId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return passwordHashGeneratorLocalService.deletePasswordHashGenerator(
			(PasswordHashGenerator)persistedModel);
	}

	public BasePersistence<PasswordHashGenerator> getBasePersistence() {
		return passwordHashGeneratorPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return passwordHashGeneratorPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns the password hash generator with the matching UUID and company.
	 *
	 * @param uuid the password hash generator's UUID
	 * @param companyId the primary key of the company
	 * @return the matching password hash generator
	 * @throws PortalException if a matching password hash generator could not be found
	 */
	@Override
	public PasswordHashGenerator getPasswordHashGeneratorByUuidAndCompanyId(
			String uuid, long companyId)
		throws PortalException {

		return passwordHashGeneratorPersistence.findByUuid_C_First(
			uuid, companyId, null);
	}

	/**
	 * Returns a range of all the password hash generators.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.portal.security.password.model.impl.PasswordHashGeneratorModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of password hash generators
	 * @param end the upper bound of the range of password hash generators (not inclusive)
	 * @return the range of password hash generators
	 */
	@Override
	public List<PasswordHashGenerator> getPasswordHashGenerators(
		int start, int end) {

		return passwordHashGeneratorPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of password hash generators.
	 *
	 * @return the number of password hash generators
	 */
	@Override
	public int getPasswordHashGeneratorsCount() {
		return passwordHashGeneratorPersistence.countAll();
	}

	/**
	 * Updates the password hash generator in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PasswordHashGeneratorLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param passwordHashGenerator the password hash generator
	 * @return the password hash generator that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public PasswordHashGenerator updatePasswordHashGenerator(
		PasswordHashGenerator passwordHashGenerator) {

		return passwordHashGeneratorPersistence.update(passwordHashGenerator);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			PasswordHashGeneratorLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		passwordHashGeneratorLocalService =
			(PasswordHashGeneratorLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return PasswordHashGeneratorLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return PasswordHashGenerator.class;
	}

	protected String getModelClassName() {
		return PasswordHashGenerator.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				passwordHashGeneratorPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected PasswordEntryPersistence passwordEntryPersistence;

	protected PasswordHashGeneratorLocalService
		passwordHashGeneratorLocalService;

	@Reference
	protected PasswordHashGeneratorPersistence passwordHashGeneratorPersistence;

	@Reference
	protected PasswordMetaPersistence passwordMetaPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}