/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.security.password.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.security.password.model.PasswordHashGenerator;
import com.liferay.portal.security.password.model.PasswordHashGeneratorModel;
import com.liferay.portal.security.password.model.PasswordHashGeneratorSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PasswordHashGenerator service. Represents a row in the &quot;PasswordHashGenerator&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PasswordHashGeneratorModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PasswordHashGeneratorImpl}.
 * </p>
 *
 * @author Arthur Chan
 * @see PasswordHashGeneratorImpl
 * @generated
 */
@JSON(strict = true)
public class PasswordHashGeneratorModelImpl
	extends BaseModelImpl<PasswordHashGenerator>
	implements PasswordHashGeneratorModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a password hash generator model instance should use the <code>PasswordHashGenerator</code> interface instead.
	 */
	public static final String TABLE_NAME = "PasswordHashGenerator";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"uuid_", Types.VARCHAR},
		{"passwordHashGeneratorId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"hashGeneratorName", Types.VARCHAR},
		{"hashGeneratorMeta", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("passwordHashGeneratorId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("hashGeneratorName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("hashGeneratorMeta", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PasswordHashGenerator (mvccVersion LONG default 0 not null,uuid_ VARCHAR(75) null,passwordHashGeneratorId LONG not null primary key,companyId LONG,createDate DATE null,hashGeneratorName VARCHAR(75) null,hashGeneratorMeta VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table PasswordHashGenerator";

	public static final String ORDER_BY_JPQL =
		" ORDER BY passwordHashGenerator.createDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY PasswordHashGenerator.createDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long CREATEDATE_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static PasswordHashGenerator toModel(
		PasswordHashGeneratorSoap soapModel) {

		if (soapModel == null) {
			return null;
		}

		PasswordHashGenerator model = new PasswordHashGeneratorImpl();

		model.setMvccVersion(soapModel.getMvccVersion());
		model.setUuid(soapModel.getUuid());
		model.setPasswordHashGeneratorId(
			soapModel.getPasswordHashGeneratorId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setCreateDate(soapModel.getCreateDate());
		model.setHashGeneratorName(soapModel.getHashGeneratorName());
		model.setHashGeneratorMeta(soapModel.getHashGeneratorMeta());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<PasswordHashGenerator> toModels(
		PasswordHashGeneratorSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<PasswordHashGenerator> models =
			new ArrayList<PasswordHashGenerator>(soapModels.length);

		for (PasswordHashGeneratorSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public PasswordHashGeneratorModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _passwordHashGeneratorId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPasswordHashGeneratorId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _passwordHashGeneratorId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PasswordHashGenerator.class;
	}

	@Override
	public String getModelClassName() {
		return PasswordHashGenerator.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PasswordHashGenerator, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PasswordHashGenerator, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PasswordHashGenerator, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PasswordHashGenerator)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PasswordHashGenerator, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PasswordHashGenerator, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PasswordHashGenerator)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PasswordHashGenerator, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PasswordHashGenerator, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, PasswordHashGenerator>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			PasswordHashGenerator.class.getClassLoader(),
			PasswordHashGenerator.class, ModelWrapper.class);

		try {
			Constructor<PasswordHashGenerator> constructor =
				(Constructor<PasswordHashGenerator>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<PasswordHashGenerator, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<PasswordHashGenerator, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<PasswordHashGenerator, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<PasswordHashGenerator, Object>>();
		Map<String, BiConsumer<PasswordHashGenerator, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<PasswordHashGenerator, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", PasswordHashGenerator::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<PasswordHashGenerator, Long>)
				PasswordHashGenerator::setMvccVersion);
		attributeGetterFunctions.put("uuid", PasswordHashGenerator::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<PasswordHashGenerator, String>)
				PasswordHashGenerator::setUuid);
		attributeGetterFunctions.put(
			"passwordHashGeneratorId",
			PasswordHashGenerator::getPasswordHashGeneratorId);
		attributeSetterBiConsumers.put(
			"passwordHashGeneratorId",
			(BiConsumer<PasswordHashGenerator, Long>)
				PasswordHashGenerator::setPasswordHashGeneratorId);
		attributeGetterFunctions.put(
			"companyId", PasswordHashGenerator::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<PasswordHashGenerator, Long>)
				PasswordHashGenerator::setCompanyId);
		attributeGetterFunctions.put(
			"createDate", PasswordHashGenerator::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<PasswordHashGenerator, Date>)
				PasswordHashGenerator::setCreateDate);
		attributeGetterFunctions.put(
			"hashGeneratorName", PasswordHashGenerator::getHashGeneratorName);
		attributeSetterBiConsumers.put(
			"hashGeneratorName",
			(BiConsumer<PasswordHashGenerator, String>)
				PasswordHashGenerator::setHashGeneratorName);
		attributeGetterFunctions.put(
			"hashGeneratorMeta", PasswordHashGenerator::getHashGeneratorMeta);
		attributeSetterBiConsumers.put(
			"hashGeneratorMeta",
			(BiConsumer<PasswordHashGenerator, String>)
				PasswordHashGenerator::setHashGeneratorMeta);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getPasswordHashGeneratorId() {
		return _passwordHashGeneratorId;
	}

	@Override
	public void setPasswordHashGeneratorId(long passwordHashGeneratorId) {
		_passwordHashGeneratorId = passwordHashGeneratorId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask |= CREATEDATE_COLUMN_BITMASK;

		if (_originalCreateDate == null) {
			_originalCreateDate = _createDate;
		}

		_createDate = createDate;
	}

	public Date getOriginalCreateDate() {
		return _originalCreateDate;
	}

	@JSON
	@Override
	public String getHashGeneratorName() {
		if (_hashGeneratorName == null) {
			return "";
		}
		else {
			return _hashGeneratorName;
		}
	}

	@Override
	public void setHashGeneratorName(String hashGeneratorName) {
		_hashGeneratorName = hashGeneratorName;
	}

	@JSON
	@Override
	public String getHashGeneratorMeta() {
		if (_hashGeneratorMeta == null) {
			return "";
		}
		else {
			return _hashGeneratorMeta;
		}
	}

	@Override
	public void setHashGeneratorMeta(String hashGeneratorMeta) {
		_hashGeneratorMeta = hashGeneratorMeta;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), PasswordHashGenerator.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PasswordHashGenerator toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PasswordHashGenerator>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PasswordHashGeneratorImpl passwordHashGeneratorImpl =
			new PasswordHashGeneratorImpl();

		passwordHashGeneratorImpl.setMvccVersion(getMvccVersion());
		passwordHashGeneratorImpl.setUuid(getUuid());
		passwordHashGeneratorImpl.setPasswordHashGeneratorId(
			getPasswordHashGeneratorId());
		passwordHashGeneratorImpl.setCompanyId(getCompanyId());
		passwordHashGeneratorImpl.setCreateDate(getCreateDate());
		passwordHashGeneratorImpl.setHashGeneratorName(getHashGeneratorName());
		passwordHashGeneratorImpl.setHashGeneratorMeta(getHashGeneratorMeta());

		passwordHashGeneratorImpl.resetOriginalValues();

		return passwordHashGeneratorImpl;
	}

	@Override
	public int compareTo(PasswordHashGenerator passwordHashGenerator) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), passwordHashGenerator.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PasswordHashGenerator)) {
			return false;
		}

		PasswordHashGenerator passwordHashGenerator =
			(PasswordHashGenerator)object;

		long primaryKey = passwordHashGenerator.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		_originalUuid = _uuid;

		_originalCompanyId = _companyId;

		_setOriginalCompanyId = false;

		_originalCreateDate = _createDate;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PasswordHashGenerator> toCacheModel() {
		PasswordHashGeneratorCacheModel passwordHashGeneratorCacheModel =
			new PasswordHashGeneratorCacheModel();

		passwordHashGeneratorCacheModel.mvccVersion = getMvccVersion();

		passwordHashGeneratorCacheModel.uuid = getUuid();

		String uuid = passwordHashGeneratorCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			passwordHashGeneratorCacheModel.uuid = null;
		}

		passwordHashGeneratorCacheModel.passwordHashGeneratorId =
			getPasswordHashGeneratorId();

		passwordHashGeneratorCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			passwordHashGeneratorCacheModel.createDate = createDate.getTime();
		}
		else {
			passwordHashGeneratorCacheModel.createDate = Long.MIN_VALUE;
		}

		passwordHashGeneratorCacheModel.hashGeneratorName =
			getHashGeneratorName();

		String hashGeneratorName =
			passwordHashGeneratorCacheModel.hashGeneratorName;

		if ((hashGeneratorName != null) && (hashGeneratorName.length() == 0)) {
			passwordHashGeneratorCacheModel.hashGeneratorName = null;
		}

		passwordHashGeneratorCacheModel.hashGeneratorMeta =
			getHashGeneratorMeta();

		String hashGeneratorMeta =
			passwordHashGeneratorCacheModel.hashGeneratorMeta;

		if ((hashGeneratorMeta != null) && (hashGeneratorMeta.length() == 0)) {
			passwordHashGeneratorCacheModel.hashGeneratorMeta = null;
		}

		return passwordHashGeneratorCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PasswordHashGenerator, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PasswordHashGenerator, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PasswordHashGenerator, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((PasswordHashGenerator)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<PasswordHashGenerator, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<PasswordHashGenerator, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PasswordHashGenerator, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((PasswordHashGenerator)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PasswordHashGenerator>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _mvccVersion;
	private String _uuid;
	private String _originalUuid;
	private long _passwordHashGeneratorId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private Date _createDate;
	private Date _originalCreateDate;
	private String _hashGeneratorName;
	private String _hashGeneratorMeta;
	private long _columnBitmask;
	private PasswordHashGenerator _escapedModel;

}