/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.security.audit.storage.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.security.audit.storage.model.AuditPseudonym;
import com.liferay.portal.security.audit.storage.model.AuditPseudonymModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the AuditPseudonym service. Represents a row in the &quot;Audit_AuditPseudonym&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AuditPseudonymModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AuditPseudonymImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AuditPseudonymImpl
 * @generated
 */
public class AuditPseudonymModelImpl
	extends BaseModelImpl<AuditPseudonym> implements AuditPseudonymModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a audit pseudonym model instance should use the <code>AuditPseudonym</code> interface instead.
	 */
	public static final String TABLE_NAME = "Audit_AuditPseudonym";

	public static final Object[][] TABLE_COLUMNS = {
		{"auditPseudonymId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"createDate", Types.TIMESTAMP}, {"contextName", Types.VARCHAR},
		{"fieldCategory", Types.VARCHAR}, {"value", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("auditPseudonymId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("contextName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("fieldCategory", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("value", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Audit_AuditPseudonym (auditPseudonymId LONG not null primary key,companyId LONG,createDate DATE null,contextName VARCHAR(75) null,fieldCategory VARCHAR(75) null,value VARCHAR(255) null)";

	public static final String TABLE_SQL_DROP =
		"drop table Audit_AuditPseudonym";

	public static final String ENTITY_ALIAS = "auditPseudonym";

	public static final String ORDER_BY_JPQL =
		" ORDER BY auditPseudonym.auditPseudonymId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Audit_AuditPseudonym.auditPseudonymId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CONTEXTNAME_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FIELDCATEGORY_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long VALUE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long AUDITPSEUDONYMID_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AuditPseudonymModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _auditPseudonymId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAuditPseudonymId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _auditPseudonymId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AuditPseudonym.class;
	}

	@Override
	public String getModelClassName() {
		return AuditPseudonym.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AuditPseudonym, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AuditPseudonym, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AuditPseudonym, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AuditPseudonym)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AuditPseudonym, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AuditPseudonym, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AuditPseudonym)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AuditPseudonym, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AuditPseudonym, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<AuditPseudonym, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<AuditPseudonym, Object>>
				attributeGetterFunctions =
					new LinkedHashMap
						<String, Function<AuditPseudonym, Object>>();

			attributeGetterFunctions.put(
				"auditPseudonymId", AuditPseudonym::getAuditPseudonymId);
			attributeGetterFunctions.put(
				"companyId", AuditPseudonym::getCompanyId);
			attributeGetterFunctions.put(
				"createDate", AuditPseudonym::getCreateDate);
			attributeGetterFunctions.put(
				"contextName", AuditPseudonym::getContextName);
			attributeGetterFunctions.put(
				"fieldCategory", AuditPseudonym::getFieldCategory);
			attributeGetterFunctions.put("value", AuditPseudonym::getValue);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<AuditPseudonym, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<AuditPseudonym, ?>>
				attributeSetterBiConsumers =
					new LinkedHashMap<String, BiConsumer<AuditPseudonym, ?>>();

			attributeSetterBiConsumers.put(
				"auditPseudonymId",
				(BiConsumer<AuditPseudonym, Long>)
					AuditPseudonym::setAuditPseudonymId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<AuditPseudonym, Long>)AuditPseudonym::setCompanyId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<AuditPseudonym, Date>)
					AuditPseudonym::setCreateDate);
			attributeSetterBiConsumers.put(
				"contextName",
				(BiConsumer<AuditPseudonym, String>)
					AuditPseudonym::setContextName);
			attributeSetterBiConsumers.put(
				"fieldCategory",
				(BiConsumer<AuditPseudonym, String>)
					AuditPseudonym::setFieldCategory);
			attributeSetterBiConsumers.put(
				"value",
				(BiConsumer<AuditPseudonym, String>)AuditPseudonym::setValue);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public long getAuditPseudonymId() {
		return _auditPseudonymId;
	}

	@Override
	public void setAuditPseudonymId(long auditPseudonymId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_auditPseudonymId = auditPseudonymId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public String getContextName() {
		if (_contextName == null) {
			return "";
		}
		else {
			return _contextName;
		}
	}

	@Override
	public void setContextName(String contextName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_contextName = contextName;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalContextName() {
		return getColumnOriginalValue("contextName");
	}

	@Override
	public String getFieldCategory() {
		if (_fieldCategory == null) {
			return "";
		}
		else {
			return _fieldCategory;
		}
	}

	@Override
	public void setFieldCategory(String fieldCategory) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_fieldCategory = fieldCategory;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalFieldCategory() {
		return getColumnOriginalValue("fieldCategory");
	}

	@Override
	public String getValue() {
		if (_value == null) {
			return "";
		}
		else {
			return _value;
		}
	}

	@Override
	public void setValue(String value) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_value = value;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalValue() {
		return getColumnOriginalValue("value");
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), AuditPseudonym.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AuditPseudonym toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AuditPseudonym>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AuditPseudonymImpl auditPseudonymImpl = new AuditPseudonymImpl();

		auditPseudonymImpl.setAuditPseudonymId(getAuditPseudonymId());
		auditPseudonymImpl.setCompanyId(getCompanyId());
		auditPseudonymImpl.setCreateDate(getCreateDate());
		auditPseudonymImpl.setContextName(getContextName());
		auditPseudonymImpl.setFieldCategory(getFieldCategory());
		auditPseudonymImpl.setValue(getValue());

		auditPseudonymImpl.resetOriginalValues();

		return auditPseudonymImpl;
	}

	@Override
	public AuditPseudonym cloneWithOriginalValues() {
		AuditPseudonymImpl auditPseudonymImpl = new AuditPseudonymImpl();

		auditPseudonymImpl.setAuditPseudonymId(
			this.<Long>getColumnOriginalValue("auditPseudonymId"));
		auditPseudonymImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		auditPseudonymImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		auditPseudonymImpl.setContextName(
			this.<String>getColumnOriginalValue("contextName"));
		auditPseudonymImpl.setFieldCategory(
			this.<String>getColumnOriginalValue("fieldCategory"));
		auditPseudonymImpl.setValue(
			this.<String>getColumnOriginalValue("value"));

		return auditPseudonymImpl;
	}

	@Override
	public int compareTo(AuditPseudonym auditPseudonym) {
		long primaryKey = auditPseudonym.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AuditPseudonym)) {
			return false;
		}

		AuditPseudonym auditPseudonym = (AuditPseudonym)object;

		long primaryKey = auditPseudonym.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AuditPseudonym> toCacheModel() {
		AuditPseudonymCacheModel auditPseudonymCacheModel =
			new AuditPseudonymCacheModel();

		auditPseudonymCacheModel.auditPseudonymId = getAuditPseudonymId();

		auditPseudonymCacheModel.companyId = getCompanyId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			auditPseudonymCacheModel.createDate = createDate.getTime();
		}
		else {
			auditPseudonymCacheModel.createDate = Long.MIN_VALUE;
		}

		auditPseudonymCacheModel.contextName = getContextName();

		String contextName = auditPseudonymCacheModel.contextName;

		if ((contextName != null) && (contextName.length() == 0)) {
			auditPseudonymCacheModel.contextName = null;
		}

		auditPseudonymCacheModel.fieldCategory = getFieldCategory();

		String fieldCategory = auditPseudonymCacheModel.fieldCategory;

		if ((fieldCategory != null) && (fieldCategory.length() == 0)) {
			auditPseudonymCacheModel.fieldCategory = null;
		}

		auditPseudonymCacheModel.value = getValue();

		String value = auditPseudonymCacheModel.value;

		if ((value != null) && (value.length() == 0)) {
			auditPseudonymCacheModel.value = null;
		}

		return auditPseudonymCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AuditPseudonym, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AuditPseudonym, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AuditPseudonym, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((AuditPseudonym)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AuditPseudonym>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AuditPseudonym.class, ModelWrapper.class);

	}

	private long _auditPseudonymId;
	private long _companyId;
	private Date _createDate;
	private String _contextName;
	private String _fieldCategory;
	private String _value;

	public <T> T getColumnValue(String columnName) {
		Function<AuditPseudonym, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AuditPseudonym)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("auditPseudonymId", _auditPseudonymId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("contextName", _contextName);
		_columnOriginalValues.put("fieldCategory", _fieldCategory);
		_columnOriginalValues.put("value", _value);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("auditPseudonymId", 1L);

		columnBitmasks.put("companyId", 2L);

		columnBitmasks.put("createDate", 4L);

		columnBitmasks.put("contextName", 8L);

		columnBitmasks.put("fieldCategory", 16L);

		columnBitmasks.put("value", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AuditPseudonym _escapedModel;

}
// LIFERAY-SERVICE-BUILDER-HASH:1519830501