/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.liferay.portal.security.audit.storage.model.impl;

import com.liferay.portal.security.audit.storage.model.AuditPseudonym;
import com.liferay.portal.security.audit.storage.service.AuditPseudonymLocalServiceUtil;

/**
 * The extended model base implementation for the AuditPseudonym service. Represents a row in the &quot;Audit_AuditPseudonym&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AuditPseudonymImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AuditPseudonymImpl
 * @see AuditPseudonym
 * @generated
 */
public abstract class AuditPseudonymBaseImpl
	extends AuditPseudonymModelImpl implements AuditPseudonym {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a audit pseudonym model instance should use the <code>AuditPseudonym</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			AuditPseudonymLocalServiceUtil.addAuditPseudonym(this);
		}
		else {
			AuditPseudonymLocalServiceUtil.updateAuditPseudonym(this);
		}
	}

}
// LIFERAY-SERVICE-BUILDER-HASH:-802440910