/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.security.ldap.persistence.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;
import com.liferay.portal.kernel.util.Validator;
import com.liferay.portal.security.ldap.persistence.model.LDAPServerAttributeRel;
import com.liferay.portal.security.ldap.persistence.model.LDAPServerAttributeRelModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the LDAPServerAttributeRel service. Represents a row in the &quot;LDAPServerAttributeRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>LDAPServerAttributeRelModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LDAPServerAttributeRelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LDAPServerAttributeRelImpl
 * @generated
 */
public class LDAPServerAttributeRelModelImpl
	extends BaseModelImpl<LDAPServerAttributeRel>
	implements LDAPServerAttributeRelModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ldap server attribute rel model instance should use the <code>LDAPServerAttributeRel</code> interface instead.
	 */
	public static final String TABLE_NAME = "LDAPServerAttributeRel";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT},
		{"ldapServerAttributeRelId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"ldapServerId", Types.BIGINT}, {"classNameId", Types.BIGINT},
		{"classPK", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ldapServerAttributeRelId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ldapServerId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classNameId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("classPK", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table LDAPServerAttributeRel (mvccVersion LONG default 0 not null,ldapServerAttributeRelId LONG not null primary key,companyId LONG,ldapServerId LONG,classNameId LONG,classPK LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table LDAPServerAttributeRel";

	public static final String ORDER_BY_JPQL =
		" ORDER BY ldapServerAttributeRel.ldapServerAttributeRelId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY LDAPServerAttributeRel.ldapServerAttributeRelId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CLASSNAMEID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CLASSPK_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LDAPSERVERID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long LDAPSERVERATTRIBUTERELID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public LDAPServerAttributeRelModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _ldapServerAttributeRelId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setLdapServerAttributeRelId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _ldapServerAttributeRelId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LDAPServerAttributeRel.class;
	}

	@Override
	public String getModelClassName() {
		return LDAPServerAttributeRel.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<LDAPServerAttributeRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<LDAPServerAttributeRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LDAPServerAttributeRel, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((LDAPServerAttributeRel)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<LDAPServerAttributeRel, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<LDAPServerAttributeRel, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(LDAPServerAttributeRel)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<LDAPServerAttributeRel, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<LDAPServerAttributeRel, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<LDAPServerAttributeRel, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<LDAPServerAttributeRel, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<LDAPServerAttributeRel, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<LDAPServerAttributeRel, Object>>();
		Map<String, BiConsumer<LDAPServerAttributeRel, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<LDAPServerAttributeRel, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", LDAPServerAttributeRel::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<LDAPServerAttributeRel, Long>)
				LDAPServerAttributeRel::setMvccVersion);
		attributeGetterFunctions.put(
			"ldapServerAttributeRelId",
			LDAPServerAttributeRel::getLdapServerAttributeRelId);
		attributeSetterBiConsumers.put(
			"ldapServerAttributeRelId",
			(BiConsumer<LDAPServerAttributeRel, Long>)
				LDAPServerAttributeRel::setLdapServerAttributeRelId);
		attributeGetterFunctions.put(
			"companyId", LDAPServerAttributeRel::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<LDAPServerAttributeRel, Long>)
				LDAPServerAttributeRel::setCompanyId);
		attributeGetterFunctions.put(
			"ldapServerId", LDAPServerAttributeRel::getLdapServerId);
		attributeSetterBiConsumers.put(
			"ldapServerId",
			(BiConsumer<LDAPServerAttributeRel, Long>)
				LDAPServerAttributeRel::setLdapServerId);
		attributeGetterFunctions.put(
			"classNameId", LDAPServerAttributeRel::getClassNameId);
		attributeSetterBiConsumers.put(
			"classNameId",
			(BiConsumer<LDAPServerAttributeRel, Long>)
				LDAPServerAttributeRel::setClassNameId);
		attributeGetterFunctions.put(
			"classPK", LDAPServerAttributeRel::getClassPK);
		attributeSetterBiConsumers.put(
			"classPK",
			(BiConsumer<LDAPServerAttributeRel, Long>)
				LDAPServerAttributeRel::setClassPK);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_mvccVersion = mvccVersion;
	}

	@Override
	public long getLdapServerAttributeRelId() {
		return _ldapServerAttributeRelId;
	}

	@Override
	public void setLdapServerAttributeRelId(long ldapServerAttributeRelId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ldapServerAttributeRelId = ldapServerAttributeRelId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	@Override
	public long getLdapServerId() {
		return _ldapServerId;
	}

	@Override
	public void setLdapServerId(long ldapServerId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ldapServerId = ldapServerId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalLdapServerId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("ldapServerId"));
	}

	@Override
	public String getClassName() {
		if (getClassNameId() <= 0) {
			return "";
		}

		return PortalUtil.getClassName(getClassNameId());
	}

	@Override
	public void setClassName(String className) {
		long classNameId = 0;

		if (Validator.isNotNull(className)) {
			classNameId = PortalUtil.getClassNameId(className);
		}

		setClassNameId(classNameId);
	}

	@Override
	public long getClassNameId() {
		return _classNameId;
	}

	@Override
	public void setClassNameId(long classNameId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classNameId = classNameId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalClassNameId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("classNameId"));
	}

	@Override
	public long getClassPK() {
		return _classPK;
	}

	@Override
	public void setClassPK(long classPK) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_classPK = classPK;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalClassPK() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("classPK"));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), LDAPServerAttributeRel.class.getName(),
			getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LDAPServerAttributeRel toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, LDAPServerAttributeRel>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LDAPServerAttributeRelImpl ldapServerAttributeRelImpl =
			new LDAPServerAttributeRelImpl();

		ldapServerAttributeRelImpl.setMvccVersion(getMvccVersion());
		ldapServerAttributeRelImpl.setLdapServerAttributeRelId(
			getLdapServerAttributeRelId());
		ldapServerAttributeRelImpl.setCompanyId(getCompanyId());
		ldapServerAttributeRelImpl.setLdapServerId(getLdapServerId());
		ldapServerAttributeRelImpl.setClassNameId(getClassNameId());
		ldapServerAttributeRelImpl.setClassPK(getClassPK());

		ldapServerAttributeRelImpl.resetOriginalValues();

		return ldapServerAttributeRelImpl;
	}

	@Override
	public LDAPServerAttributeRel cloneWithOriginalValues() {
		LDAPServerAttributeRelImpl ldapServerAttributeRelImpl =
			new LDAPServerAttributeRelImpl();

		ldapServerAttributeRelImpl.setMvccVersion(
			this.<Long>getColumnOriginalValue("mvccVersion"));
		ldapServerAttributeRelImpl.setLdapServerAttributeRelId(
			this.<Long>getColumnOriginalValue("ldapServerAttributeRelId"));
		ldapServerAttributeRelImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		ldapServerAttributeRelImpl.setLdapServerId(
			this.<Long>getColumnOriginalValue("ldapServerId"));
		ldapServerAttributeRelImpl.setClassNameId(
			this.<Long>getColumnOriginalValue("classNameId"));
		ldapServerAttributeRelImpl.setClassPK(
			this.<Long>getColumnOriginalValue("classPK"));

		return ldapServerAttributeRelImpl;
	}

	@Override
	public int compareTo(LDAPServerAttributeRel ldapServerAttributeRel) {
		long primaryKey = ldapServerAttributeRel.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof LDAPServerAttributeRel)) {
			return false;
		}

		LDAPServerAttributeRel ldapServerAttributeRel =
			(LDAPServerAttributeRel)object;

		long primaryKey = ldapServerAttributeRel.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<LDAPServerAttributeRel> toCacheModel() {
		LDAPServerAttributeRelCacheModel ldapServerAttributeRelCacheModel =
			new LDAPServerAttributeRelCacheModel();

		ldapServerAttributeRelCacheModel.mvccVersion = getMvccVersion();

		ldapServerAttributeRelCacheModel.ldapServerAttributeRelId =
			getLdapServerAttributeRelId();

		ldapServerAttributeRelCacheModel.companyId = getCompanyId();

		ldapServerAttributeRelCacheModel.ldapServerId = getLdapServerId();

		ldapServerAttributeRelCacheModel.classNameId = getClassNameId();

		ldapServerAttributeRelCacheModel.classPK = getClassPK();

		return ldapServerAttributeRelCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<LDAPServerAttributeRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<LDAPServerAttributeRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LDAPServerAttributeRel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(LDAPServerAttributeRel)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<LDAPServerAttributeRel, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<LDAPServerAttributeRel, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<LDAPServerAttributeRel, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((LDAPServerAttributeRel)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, LDAPServerAttributeRel>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					LDAPServerAttributeRel.class, ModelWrapper.class);

	}

	private long _mvccVersion;
	private long _ldapServerAttributeRelId;
	private long _companyId;
	private long _ldapServerId;
	private long _classNameId;
	private long _classPK;

	public <T> T getColumnValue(String columnName) {
		Function<LDAPServerAttributeRel, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((LDAPServerAttributeRel)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("mvccVersion", _mvccVersion);
		_columnOriginalValues.put(
			"ldapServerAttributeRelId", _ldapServerAttributeRelId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("ldapServerId", _ldapServerId);
		_columnOriginalValues.put("classNameId", _classNameId);
		_columnOriginalValues.put("classPK", _classPK);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("mvccVersion", 1L);

		columnBitmasks.put("ldapServerAttributeRelId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("ldapServerId", 8L);

		columnBitmasks.put("classNameId", 16L);

		columnBitmasks.put("classPK", 32L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private LDAPServerAttributeRel _escapedModel;

}