/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.portal.security.password.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PasswordHashGenerator service. Represents a row in the &quot;PasswordHashGenerator&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.portal.security.password.model.impl.PasswordHashGeneratorModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.portal.security.password.model.impl.PasswordHashGeneratorImpl</code>.
 * </p>
 *
 * @author Arthur Chan
 * @see PasswordHashGenerator
 * @generated
 */
@ProviderType
public interface PasswordHashGeneratorModel
	extends BaseModel<PasswordHashGenerator>, MVCCModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a password hash generator model instance should use the {@link PasswordHashGenerator} interface instead.
	 */

	/**
	 * Returns the primary key of this password hash generator.
	 *
	 * @return the primary key of this password hash generator
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this password hash generator.
	 *
	 * @param primaryKey the primary key of this password hash generator
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this password hash generator.
	 *
	 * @return the mvcc version of this password hash generator
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this password hash generator.
	 *
	 * @param mvccVersion the mvcc version of this password hash generator
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this password hash generator.
	 *
	 * @return the uuid of this password hash generator
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this password hash generator.
	 *
	 * @param uuid the uuid of this password hash generator
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the password hash generator ID of this password hash generator.
	 *
	 * @return the password hash generator ID of this password hash generator
	 */
	public long getPasswordHashGeneratorId();

	/**
	 * Sets the password hash generator ID of this password hash generator.
	 *
	 * @param passwordHashGeneratorId the password hash generator ID of this password hash generator
	 */
	public void setPasswordHashGeneratorId(long passwordHashGeneratorId);

	/**
	 * Returns the company ID of this password hash generator.
	 *
	 * @return the company ID of this password hash generator
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this password hash generator.
	 *
	 * @param companyId the company ID of this password hash generator
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this password hash generator.
	 *
	 * @return the create date of this password hash generator
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this password hash generator.
	 *
	 * @param createDate the create date of this password hash generator
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the hash generator name of this password hash generator.
	 *
	 * @return the hash generator name of this password hash generator
	 */
	@AutoEscape
	public String getHashGeneratorName();

	/**
	 * Sets the hash generator name of this password hash generator.
	 *
	 * @param hashGeneratorName the hash generator name of this password hash generator
	 */
	public void setHashGeneratorName(String hashGeneratorName);

	/**
	 * Returns the hash generator meta of this password hash generator.
	 *
	 * @return the hash generator meta of this password hash generator
	 */
	@AutoEscape
	public String getHashGeneratorMeta();

	/**
	 * Sets the hash generator meta of this password hash generator.
	 *
	 * @param hashGeneratorMeta the hash generator meta of this password hash generator
	 */
	public void setHashGeneratorMeta(String hashGeneratorMeta);

}